# Generated by Django 3.1.4 on 2023-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.FileField(upload_to='comments/pdfs/', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='blog/static/blog/Content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='testing.jpeg', upload_to='blog/static/blog/Thumbnail', verbose_name='Thumbnail'),
        ),
    ]
